# v1.1.2alpha
---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: PMM                        | Clean YUM cache
      command: /usr/bin/yum --enablerepo=pmm clean all
      changed_when: False

    - name: PMM                        | Install RPMs
      when: ansible_os_family == 'RedHat'
      yum: name={{ item }} state=present enablerepo=pmm
      with_items:
        - nginx
        - pmm-update
        - percona-toolkit-3.0.1
        - percona-dashboards-1.1.2
        - pmm-server-1.1.2
        - percona-orchestrator-2.0.3
        - percona-prometheus-1.5.2
        - percona-node_exporter-0.13.0
        - percona-qan-api-1.1.2
        - percona-grafana-4.2.0
        - percona-qan-app-1.1.2
        - pmm-manage-1.1.2
        - percona-consul-0.7.5

    - name: PMM                        | Import dashboards
      command: bash -c "/usr/share/percona-dashboards/import-dashboards.py $(dirname $(ls /srv/grafana/grafana.db /var/lib/grafana/grafana.db 2>/dev/null))"
      register: import_result
      changed_when: "'up-to-date' not in import_result.stdout"
