# v1.1.3
---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: PMM                        | Clean YUM cache
      command: /usr/bin/yum --enablerepo=pmm clean all
      changed_when: False

    - name: PMM                        | Install RPMs
      when: ansible_os_family == 'RedHat'
      yum: name={{ item }} state=present enablerepo=pmm
      with_items:
        - nginx
        - pmm-update
        - percona-toolkit-3.0.1
        - percona-dashboards-1.1.3
        - pmm-server-1.1.3
        - percona-orchestrator-2.1.0
        - percona-prometheus-1.6.1
        - percona-node_exporter-0.13.0
        - percona-qan-api-1.1.3
        - percona-grafana-4.2.0
        - percona-qan-app-1.1.3
        - pmm-manage-1.1.3
        - percona-consul-0.8.1

    - name: PMM                        | Check .dockerenv file
      stat: path=/.dockerenv
      register: dockerenv

    - name: NGINX                      | Disable daemon
      when: dockerenv.stat.exists
      lineinfile:
        dest: /etc/nginx/nginx.conf
        line: 'daemon off;'

    - name: NGINX                      | Disable password-page
      when: dockerenv.stat.exists
      replace:
        dest: /etc/nginx/conf.d/pmm.conf
        regexp: '/usr/share/pmm-server/password-page'
        replace: '/usr/share/pmm-server/landing-page'

    - name: NGINX                      | Fix nginx config
      replace:
        dest: /etc/nginx/nginx.conf
        regexp: '^(\s*)listen'
        replace: '\1#listen'

    - name: PMM                        | Import dashboards
      command: bash -c "/usr/share/percona-dashboards/import-dashboards.py $(dirname $(ls /srv/grafana/grafana.db /var/lib/grafana/grafana.db 2>/dev/null))"
      register: import_result
      changed_when: "'up-to-date' not in import_result.stdout"

    - name: PMM                        | Stat supervisor
      stat: path=/usr/bin/supervisorctl
      register: supervisorctl

    - name: PMM                        | Restart services (supervisord)
      when: supervisorctl.stat.exists
      command: /usr/bin/supervisorctl restart all

    - name: PMM                        | Restart services (systemd)
      when: not supervisorctl.stat.exists
      service: name={{ item }} state=restarted
      with_items:
        - orchestrator
        - prometheus
        - node_exporter
        - percona-qan-api
        - grafana-server
        - consul
